apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: istio
    release: metrics
  name: istio-federate
  namespace: istio-system
spec:
  endpoints:
  - interval: 30s
    scrapeTimeout: 30s
    params:
      'match[]':
      - '{job="istio-mesh"}'
      - '{job="envoy-stats"}'
      - '{job="istio-telemetry"}'
      - '{job="pilot"}'
    path: /federate
    port: http-prometheus
    honorLabels: true
    relabelings:
    - action: keep
      regex: '^prometheus$'
      sourceLabels:
      - '__meta_kubernetes_pod_container_name'
  jobLabel: app
  namespaceSelector:
    matchNames:
    - istio-system
  selector:
    matchLabels:
      app: prometheus

